package migrations

import (
	"landmark-api/internal/models"
	"log"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// Landmarks is a slice of Landmark objects
var Landmarks = []models.Landmark{
	{
		ID:          uuid.New(),
		Name:        "Eiffel Tower",
		Description: "Iconic iron lattice tower on the Champ de Mars.",
		Latitude:    48.8584,
		Longitude:   2.2945,
		Country:     "France",
		City:        "Paris",
		Category:    "Monument",
		ImageUrl:    "https://source.unsplash.com/featured/?eiffel-tower",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		ID:          uuid.New(),
		Name:        "Colosseum",
		Description: "Ancient amphitheater in the center of Rome.",
		Latitude:    41.8902,
		Longitude:   12.4922,
		Country:     "Italy",
		City:        "Rome",
		Category:    "Monument",
		ImageUrl:    "https://source.unsplash.com/featured/?colosseum",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		ID:          uuid.New(),
		Name:        "Great Wall of China",
		Description: "Ancient series of walls and fortifications.",
		Latitude:    40.4319,
		Longitude:   116.5704,
		Country:     "China",
		City:        "Beijing",
		Category:    "Historical Site",
		ImageUrl:    "https://source.unsplash.com/featured/?great-wall-of-china",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		ID:          uuid.New(),
		Name:        "Machu Picchu",
		Description: "Inca citadel set high in the Andes Mountains.",
		Latitude:    -13.1631,
		Longitude:   -72.5449,
		Country:     "Peru",
		City:        "Cusco Region",
		Category:    "Historical Site",
		ImageUrl:    "https://source.unsplash.com/featured/?machu-picchu",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		ID:          uuid.New(),
		Name:        "Statue of Liberty",
		Description: "Symbol of freedom and democracy.",
		Latitude:    40.6892,
		Longitude:   -74.0445,
		Country:     "USA",
		City:        "New York",
		Category:    "Monument",
		ImageUrl:    "https://source.unsplash.com/featured/?statue-of-liberty",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		ID:          uuid.New(),
		Name:        "Taj Mahal",
		Description: "Mausoleum made of white marble, built in memory of Mumtaz Mahal.",
		Latitude:    27.1751,
		Longitude:   78.0421,
		Country:     "India",
		City:        "Agra",
		Category:    "Historical Site",
		ImageUrl:    "https://source.unsplash.com/featured/?taj-mahal",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		ID:          uuid.New(),
		Name:        "Sydney Opera House",
		Description: "Multi-venue performing arts center.",
		Latitude:    -33.8568,
		Longitude:   151.2153,
		Country:     "Australia",
		City:        "Sydney",
		Category:    "Cultural Site",
		ImageUrl:    "https://source.unsplash.com/featured/?sydney-opera-house",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		ID:          uuid.New(),
		Name:        "Christ the Redeemer",
		Description: "Statue of Jesus Christ in Rio de Janeiro.",
		Latitude:    -22.9519,
		Longitude:   -43.2105,
		Country:     "Brazil",
		City:        "Rio de Janeiro",
		Category:    "Monument",
		ImageUrl:    "https://source.unsplash.com/featured/?christ-the-redeemer",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		ID:          uuid.New(),
		Name:        "Pyramids of Giza",
		Description: "Ancient pyramid structures that are one of the Seven Wonders of the Ancient World.",
		Latitude:    29.9792,
		Longitude:   31.1342,
		Country:     "Egypt",
		City:        "Giza",
		Category:    "Historical Site",
		ImageUrl:    "https://source.unsplash.com/featured/?pyramids-of-giza",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		ID:          uuid.New(),
		Name:        "Acropolis of Athens",
		Description: "Ancient citadel containing several buildings of great architectural and historic significance.",
		Latitude:    37.9715,
		Longitude:   23.7267,
		Country:     "Greece",
		City:        "Athens",
		Category:    "Historical Site",
		ImageUrl:    "https://source.unsplash.com/featured/?acropolis",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		ID:          uuid.New(),
		Name:        "Stonehenge",
		Description: "Prehistoric monument consisting of a ring of standing stones.",
		Latitude:    51.1789,
		Longitude:   -1.8262,
		Country:     "UK",
		City:        "Wiltshire",
		Category:    "Historical Site",
		ImageUrl:    "https://source.unsplash.com/featured/?stonehenge",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		ID:          uuid.New(),
		Name:        "Hagia Sophia",
		Description: "Former Greek Orthodox Christian basilica and mosque, now a museum.",
		Latitude:    41.0082,
		Longitude:   28.9784,
		Country:     "Turkey",
		City:        "Istanbul",
		Category:    "Cultural Site",
		ImageUrl:    "https://source.unsplash.com/featured/?hagia-sophia",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		ID:          uuid.New(),
		Name:        "Burj Khalifa",
		Description: "The tallest building in the world.",
		Latitude:    25.1972,
		Longitude:   55.2744,
		Country:     "UAE",
		City:        "Dubai",
		Category:    "Modern Architecture",
		ImageUrl:    "https://source.unsplash.com/featured/?burj-khalifa",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},

	// 11-20
	{
		ID:          uuid.New(),
		Name:        "Sagrada Familia",
		Description: "Unfinished Roman Catholic basilica designed by Antoni Gaudí.",
		Latitude:    41.4036,
		Longitude:   2.1744,
		Country:     "Spain",
		City:        "Barcelona",
		Category:    "Cultural Site",
		ImageUrl:    "https://source.unsplash.com/featured/?sagrada-familia",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},
	{
		ID:          uuid.New(),
		Name:        "Big Ben",
		Description: "The Great Bell of the clock at the north end of the Palace of Westminster.",
		Latitude:    51.5007,
		Longitude:   -0.1246,
		Country:     "UK",
		City:        "London",
		Category:    "Monument",
		ImageUrl:    "https://source.unsplash.com/featured/?big-ben",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
	},

	// Add more landmarks here...
}

// LandmarkDetails is a slice of LandmarkDetail objects
var LandmarkDetails = []models.LandmarkDetail{
	{
		ID:                     uuid.New(),
		LandmarkID:             Landmarks[0].ID,
		OpeningHours:           map[string]string{"Monday": "9 AM - 12 AM", "Tuesday": "9 AM - 12 AM"},
		TicketPrices:           map[string]float64{"Adult": 25.00, "Child": 12.00},
		HistoricalSignificance: "A global cultural icon of France.",
		VisitorTips:            "Visit early in the morning to avoid crowds.",
		AccessibilityInfo:      "Wheelchair accessible.",
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
	},
	{
		ID:                     uuid.New(),
		LandmarkID:             Landmarks[1].ID,
		OpeningHours:           map[string]string{"Monday": "9 AM - 7 PM", "Tuesday": "9 AM - 7 PM"},
		TicketPrices:           map[string]float64{"Adult": 15.00, "Child": 8.00},
		HistoricalSignificance: "The largest amphitheater ever built.",
		VisitorTips:            "Book tickets in advance.",
		AccessibilityInfo:      "Accessible with assistance.",
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
	},
	{
		ID:                     uuid.New(),
		LandmarkID:             Landmarks[2].ID,
		OpeningHours:           map[string]string{"Monday": "8 AM - 5 PM", "Tuesday": "8 AM - 5 PM"},
		TicketPrices:           map[string]float64{"Adult": 10.00, "Child": 5.00},
		HistoricalSignificance: "One of the most impressive architectural feats in history.",
		VisitorTips:            "Wear comfortable shoes.",
		AccessibilityInfo:      "Not fully accessible.",
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
	},
	{
		ID:                     uuid.New(),
		LandmarkID:             Landmarks[3].ID,
		OpeningHours:           map[string]string{"Monday": "6 AM - 5 PM", "Tuesday": "6 AM - 5 PM"},
		TicketPrices:           map[string]float64{"Adult": 50.00, "Child": 25.00},
		HistoricalSignificance: "A UNESCO World Heritage Site.",
		VisitorTips:            "Stay hydrated while hiking.",
		AccessibilityInfo:      "Limited accessibility.",
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
	},
	{
		ID:                     uuid.New(),
		LandmarkID:             Landmarks[4].ID,
		OpeningHours:           map[string]string{"Monday": "9 AM - 9 PM", "Tuesday": "9 AM - 9 PM"},
		TicketPrices:           map[string]float64{"Adult": 20.00, "Child": 10.00},
		HistoricalSignificance: "Gift from France to the United States.",
		VisitorTips:            "Take a ferry for the best views.",
		AccessibilityInfo:      "Wheelchair accessible.",
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
	},
	{
		ID:                     uuid.New(),
		LandmarkID:             Landmarks[5].ID,
		OpeningHours:           map[string]string{"Monday": "6 AM - 7 PM", "Tuesday": "6 AM - 7 PM"},
		TicketPrices:           map[string]float64{"Adult": 15.00, "Child": 5.00},
		HistoricalSignificance: "A symbol of love and devotion.",
		VisitorTips:            "Visit during sunrise for fewer crowds.",
		AccessibilityInfo:      "Fully accessible.",
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
	},
	{
		ID:                     uuid.New(),
		LandmarkID:             Landmarks[6].ID,
		OpeningHours:           map[string]string{"Monday": "9 AM - 5 PM", "Tuesday": "9 AM - 5 PM"},
		TicketPrices:           map[string]float64{"Adult": 30.00, "Child": 15.00},
		HistoricalSignificance: "An architectural masterpiece.",
		VisitorTips:            "Consider a guided tour.",
		AccessibilityInfo:      "Partially accessible.",
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
	},
	{
		ID:                     uuid.New(),
		LandmarkID:             Landmarks[7].ID,
		OpeningHours:           map[string]string{"Monday": "8 AM - 10 PM", "Tuesday": "8 AM - 10 PM"},
		TicketPrices:           map[string]float64{"Adult": 30.00, "Child": 10.00},
		HistoricalSignificance: "A symbol of Christianity.",
		VisitorTips:            "Book tickets online for discounts.",
		AccessibilityInfo:      "Wheelchair accessible.",
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
	},
	{
		ID:                     uuid.New(),
		LandmarkID:             Landmarks[8].ID,
		OpeningHours:           map[string]string{"Monday": "8 AM - 4 PM", "Tuesday": "8 AM - 4 PM"},
		TicketPrices:           map[string]float64{"Adult": 10.00, "Child": 0.00},
		HistoricalSignificance: "Ancient tombs of Pharaohs.",
		VisitorTips:            "Plan your visit during winter.",
		AccessibilityInfo:      "Not accessible.",
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
	},
	{
		ID:                     uuid.New(),
		LandmarkID:             Landmarks[9].ID,
		OpeningHours:           map[string]string{"Monday": "8 AM - 8 PM", "Tuesday": "8 AM - 8 PM"},
		TicketPrices:           map[string]float64{"Adult": 12.00, "Child": 6.00},
		HistoricalSignificance: "Ancient civilization ruins.",
		VisitorTips:            "Explore nearby museums.",
		AccessibilityInfo:      "Partially accessible.",
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
	},
	{
		ID:                     uuid.New(),
		LandmarkID:             Landmarks[10].ID,
		OpeningHours:           map[string]string{"Monday": "9 AM - 5 PM", "Tuesday": "9 AM - 5 PM"},
		TicketPrices:           map[string]float64{"Adult": 30.00, "Child": 15.00},
		HistoricalSignificance: "A masterpiece of Gaudí's architecture.",
		VisitorTips:            "Check the online schedule for events.",
		AccessibilityInfo:      "Wheelchair accessible.",
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
	},
	{
		ID:                     uuid.New(),
		LandmarkID:             Landmarks[11].ID,
		OpeningHours:           map[string]string{"Monday": "9 AM - 5 PM", "Tuesday": "9 AM - 5 PM"},
		TicketPrices:           map[string]float64{"Adult": 20.00, "Child": 10.00},
		HistoricalSignificance: "An iconic symbol of London.",
		VisitorTips:            "Visit during the day for the best views.",
		AccessibilityInfo:      "Fully accessible.",
		CreatedAt:              time.Now(),
		UpdatedAt:              time.Now(),
	},

	// Add more details here...
}

// MigrateLandmarks creates the landmarks and landmark details in the database
func MigrateLandmarks(db *gorm.DB) {
	if err := db.AutoMigrate(&models.Landmark{}, &models.LandmarkDetail{}); err != nil {
		log.Fatalf("Failed to migrate: %v", err)
	}

	// Create landmarks
	for _, landmark := range Landmarks {
		if err := db.Create(&landmark).Error; err != nil {
			log.Printf("Failed to create landmark %s: %v", landmark.Name, err)
		}
	}

	// Create landmark details
	for _, detail := range LandmarkDetails {
		if err := db.Create(&detail).Error; err != nil {
			log.Printf("Failed to create landmark detail for %s: %v", detail.LandmarkID, err)
		}
	}
}
